### ISSUE TITLE
Feature Request: Wantlist Price Filtering

### ISSUE THREAD

**Issue by eberhardweber** [salcido/discogs-enhancer#121]
While Discogs Enhancer already has features to alleviate price gouging, including simply blocking sellers, there nevertheless remain reasons for wanting to apply a price filter to the "Items I Want" page. 

A large wantlist easily produces more variation and fluctuation in prices than would be ideal, and although a _generic_ price filter probably sounds slightly hamfisted, quite many webstores and webshops nevertheless have just that very filter.

Therefore, would it be possible to introduce a generic "Price Filter" function to Discogs Enhancer? Although I'm probably a "Maximum" price filter-er myself, I expect people would also want to have "Minimum" as well (both for filtering cheap finds and legitimate archival copies). Therefore the filter would have a min-max range that one could input. I fully admit currencies (and currency conversion) may complicate things further.

I've seen this mentioned in many Discogs forums posts over the years, and only finally realized Discogs Enhancer might be the weapon for this issue!

**Comment by salcido** [comment]
hey @eberhardweber sorry to leave you hanging here! Finally got some time to sit down and work on the extension. Going to start on this today and hope to have something working soon. At the very least it will have a maximum price filter and I'll try to work in a minimum as well. 

Not sure how long it will take for it to show up in the Chrome Web Store though. Google sent out an email last week saying that reviews and approvals are very slow due to coronavirus. I'll keep you posted 👍

**Comment by salcido** [comment]
Ok, this feature has been published in the `2.20.0` version. Should be updated in Chrome in the next 24 hours or so. ✌️
