### ISSUE TITLE
Adding more currencies

### ISSUE THREAD

**Issue by virgilbugnariu** [salcido/discogs-enhancer#13]
Hi Matt,

Awesome extension, thanks for making and maintaining it :).

I saw that you're serving the currency JSON from discogs-enhancer.com. 
What would it take to add additional currencies?

**Comment by virgilbugnariu** [comment]
I would've liked to add support to Romanian Leu, just for comparison reasons. I, personally, would find this really helpful. 
But I think adding support for more currencies overall would come in handy for everybody.

**Comment by salcido** [comment]
So I looked into this and it’s not as simple as just adding a new currency to the exchange rate API. 

Discogs returns price suggestions based on the currency set in the user’s seller settings. In order to use any currency not already supported by Discogs, the extension would need to know two separate currencies: the currency set in the user’s seller profile and the currency that’s unsupported (e.g.: Leu in this case). It would then need to perform two conversions to display the result. It would also end up making the UI for the Suggested Prices feature more complex and potentially confusing for users who do not need to convert to an unsupported currency. Based on that I don’t think I’m going to add support for any currencies that are not officially supported by Discogs. That being said, it will support any new currencies Discogs adds in the future.

**Comment by virgilbugnariu** [comment]
I was afraid it wouldn't be that simple :(. 
Thank you for looking into this!
