### ISSUE TITLE
Feature Request:  See full size image

### ISSUE THREAD

**Issue by jeckman** [salcido/discogs-enhancer#133]
Discogs serves images scaled down by default. There's an algorithm/method for translating the discogs provided image back into the originally uploaded one - see this forum thread:  https://www.discogs.com/forum/thread/828335

I made a js bookmarklet, that when on the page for a given image, replaces the smaller/lower quality image with the full image - also in that thread. 

Would love to see this in discogs-enhancer. Maybe not for all images by default, as that would increase discogs bandwidth and be unecessary, but as an option for when you are looking at zoomed in images

**Comment by ToastyMallows** [comment]
This is a great idea!  Like you said maybe it shouldn't be on by default or happen every time a picture loads, maybe it could be a right click menu option to load up the full-sized image in a new tab or something?

**Comment by ToastyMallows** [comment]
@salcido I'm not sure if you want to hold off on a creating a new release, but I'm currently working on this feature, should have a PR up soon enough!

**Comment by salcido** [comment]
Ah sorry, I should have replied sooner. 

As much as I would like to add this as a feature, this potentially opens up issues between copyright holders and Discogs. Discogs deliberately limits the resolution of image sizes so that rights holders can't claim that Discogs is allowing images that are clear enough for other people to copy/print for potential commercial purposes. 

So I don't want to release a feature that might cause legal issues for Discogs. Sorry again for not commenting sooner.

**Comment by ToastyMallows** [comment]
No worries!  Sadly, that does make sense 😪

**Comment by salcido** [comment]
Sorry @ToastyMallows - I feel terrible pulling the plug on your work here. 😞 I'll make an effort to stay on top of issues and keep everyone informed from now on.
