### ISSUE TITLE
Discogs Exclusives Dark Theme Support

### ISSUE THREAD

**Issue by tofuBox** [salcido/discogs-enhancer#14]
Hi there,

Just wanted to let you know that Discogs recently launched a sub-site called [Discogs-Exclusives](https://exclusives.discogs.com/).
Currently the extensions breaks certain visual aspects of the sub-site.

I am not sure if it's better for you to remove the dark theme support for that site or update this extension to support it.

**Comment by salcido** [comment]
Hi,

Thanks for the heads up. This will likely happen on any subdomain on Discogs.com due to the [`manifest.json` permissions](https://github.com/salcido/discogs-enhancer/blob/master/manifest.json#L35). 

Ideally, the extension would only affect `discogs.com` and the fix would be to set the permissions to `https://www.discogs.com/*` however, changing the permissions in an update might [disable the extension for all users](https://developer.chrome.com/extensions/permission_warnings#update_permissions). Chrome's documentation does not specify whether a change like this in permissions will cause the extension to be disabled but I am erring on the side of caution for the time being until I can get confirmation from the Chrome team that the change will not affect current users (I have opened up a thread on chromium.org's forums and am awaiting an answer).

For now, the simplest way to fix this is to just disable the dark theme when visiting `exclusives.discogs.com`. I realize this "solution" can be an annoyance but I am not willing to risk disabling the extension for every user to fix a theme issue.

**Comment by tofuBox** [comment]
I believe that you are just modifying the discogs domain permission which is currently set. According to the link you have provided, it mentions that when you add any additional permissions, it might disable the extension. 

However just as you mentioned, I think it is better for you to get confirmation from the Chrome team.

For me personally it's not an annoyance, and I don't think it is a serious issue for others as well due to the nature of that sub-site.

**Comment by salcido** [comment]
I appreciate you taking the time to open up an issue and letting me know. I'm going to try putting a check into `background.js` to disable the dark theme if the user is on `exclusives.discogs.com` and see if that causes any issues. If not, I'll push out an update until I can get confirmation on updating `manifest.json`.

**Comment by salcido** [comment]
I've added a workaround that will prevent the dark theme from running on any subdomain. The fix was added to `background.js` in order to avoid potentially disabling the extension for users.
