### ISSUE TITLE
Discogs.com subdomains: not dark-mode enabled

### ISSUE THREAD

**Issue by jimthing** [salcido/discogs-enhancer#146]
eg's: 

https://support.discogs.com
https://blog.discogs.com
https://data.discogs.com
https://localization.discogs.com

All the above subdomains show in light mode, not dark mode. ;-)

**Comment by salcido** [comment]
@jimthing Hi! Yes, this is expected behavior. [I disabled the dark theme for subdomains](https://github.com/salcido/discogs-enhancer/blob/master/js/extension/background.js#L215-L220) a few years ago to fix this issue: https://github.com/salcido/discogs-enhancer/issues/14 

There are a lot of subdomains on Discogs and more to be added in the future. Supporting a dark theme for each subdomain requires more time and energy than I am willing to give with little ROI for myself. If you would like to take up the task of updating the Dark Theme for each subdomain, please feel free to do so and submit a pull request :)

**Comment by jimthing** [comment]
@salcido Ah ok, no time for that myself, so may as well close this request. Thanks for advising.
