### ISSUE TITLE
Feature Request: Show if you already own another edition of a release

### ISSUE THREAD

**Issue by RiceTeaPrince** [salcido/discogs-enhancer#158]
Essentially, show an icon or text when viewing a list of items to purchase, as well as on the item details page, to tell you that you already own a copy of the release, but a different version. 

For example:
![image](https://user-images.githubusercontent.com/88278696/134759095-b96dd2b9-b51a-4c09-829a-18f6ce6d9fdc.png)

![image](https://user-images.githubusercontent.com/88278696/134759161-91d1b779-a583-4204-98dc-3f31e1ec2990.png)

The benefit of this is for those with larger collections who may sometimes forget which releases they may have already purchased. In my case, I have definitely done the silly thing and purchased an additional copy of something I already owned, but a different version/release...

**Comment by salcido** [comment]
Hi @RiceTeaPrince, 

Because of the number of requests the extension would have to make to do this, there is not an efficient way to solve this problem. 

Discogs limits the number of requests the extension can make to 1 per second. So it would take close to 30 seconds (at a minimum and at best) to examine each release to see if it was in your collection. 

There is another complication when you consider master releases - not all releases in the DB have master releases, so the extension would have to first check the release page and then, possibly, make another request for the master release page in order to get the collection data. This would add additional time to the overall requests effectively making this feature extremely slow to use and not very practical.
